version: 2

jobs:
  build:

    docker:
      - image: circleci/android:api-25-alpha
    working_directory: ~/edx-app-android
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      RELEASE_PK12_FILE: "../config/release.p12"
      JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-dev --fix-missing
            sudo apt-get install libfontconfig
            sudo apt-get -y install python-pip
            sudo pip install requests
      - run:
          name: Install Fastlane
          command: |
            sudo apt-get install ruby-full
            sudo gem install fastlane -NV
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
            ./gradlew dependencies --stacktrace --info
      - run:
          name: Setup project
          command: |
            git clone git@github.com:proversity-org/houston-android-config.git --branch no-branch --single-branch --depth=1 ./config
            cp -R config/fastlane fastlane
            cp -R config/metadata.py metadata.py
            cp -R config/consola_billing.py consola_billing.py
            cp -r config/gradle.properties OpenEdXMobile/gradle.properties
            cp -r config/google-services.json OpenEdXMobile/google-services.json
            echo "edx.dir = '../config'" > OpenEdXMobile/edx.properties
            mkdir -p /tmp/core_dumps
            cp -r config/config.yaml /tmp/core_dumps
      - run:
          name: Build app
          command: |
            unset ANDROID_NDK_HOME
            ./gradlew assembleProdRelease
            cp -r OpenEdXMobile/build/reports /tmp/core_dumps
            cp -r OpenEdXMobile/build/outputs /tmp/core_dumps
      - run:
          name: Deploy app
          command: |
            if [ "${CIRCLE_BRANCH}" == "no-branch" ]; then
              unset ANDROID_NDK_HOME
              ./gradlew publishApkProdRelease -PdisablePreDex -Dorg.gradle.project.track=beta --stacktrace
              fastlane supply init
              cp -R config/google-play-store-assets/icon.png fastlane/metadata/android/en-US/images/icon.png
              cp -R config/google-play-store-assets/featureGraphic.png fastlane/metadata/android/en-US/images/featureGraphic.png
              python metadata.py
              fastlane metadata
              fastlane billing
            fi
      - run:
          name: Error on gradle
          command: |
            fastlane error_on_gradle
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps

notify:
  webhooks:
    - url: https://hd0don3meg.execute-api.us-east-1.amazonaws.com/prod/consola/sendApk?organisationId=ORGANISATION_ID&projectId=PROJECT_ID&repo=edx-app-android

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: no-branch