version: 2

jobs:
  build:

    docker:
      - image: circleci/android:api-25-alpha
    working_directory: ~/edx-app-android
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      RELEASE_PK12_FILE: "../config/release.p12"
      JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: |
            sudo apt-get install ruby-full
            sudo gem install fastlane -NV
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
            ./gradlew dependencies --stacktrace --info
      - run:
          name: Setup project
          command: |
            git clone git@github.com:proversity-org/houston-android-config.git --branch c54fc9a2-3cda-11e8-b467-0ed5f89f718b --single-branch --depth=1 ./config
            cp -R config/fastlane fastlane
            cp -R config/metadata.py metadata.py
            cp -r config/gradle.properties OpenEdXMobile/gradle.properties
            cp -r config/google-services.json OpenEdXMobile/google-services.json
            echo "edx.dir = '../config'" > OpenEdXMobile/edx.properties
            mkdir -p /tmp/core_dumps
            cp -r config/config.yaml /tmp/core_dumps
      - run:
          name: Build app
          command: |
            ./gradlew assembleProdRelease
            cp -r OpenEdXMobile/build/reports /tmp/core_dumps
            cp -r OpenEdXMobile/build/outputs /tmp/core_dumps
      - deploy:
          name: Deploy app
          command: |
            if [ "${CIRCLE_BRANCH}" == "houston/c54fc9a2-3cda-11e8-b467-0ed5f89f718b" ]; then
              fastlane supply init
              python metadata.py
              fastlane metadata
              ./gradlew publishApkProdRelease -PdisablePreDex -Dorg.gradle.project.track=beta
            fi
      - store_artifacts:
          path: /tmp/core_dumps

notify:
  webhooks:
    - url: https://hd0don3meg.execute-api.us-east-1.amazonaws.com/prod/consola/sendApk?organisationId=dd0abc00-3672-11e8-835e-511823f5c61c&projectId=05353740-3674-11e8-947e-6784d62f81d9&repo=edx-app-android

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: houston/c54fc9a2-3cda-11e8-b467-0ed5f89f718b