version: 2
jobs:
  build:
     docker:
       - image: circleci/android:api-23-alpha
     environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      RELEASE_PK12_FILE: "../config/release.p12"

     steps:
       - checkout
       - run:
          name: Install pre dependencies
          command: |
             git clone git@github.com:proversity-org/edx-app-android-config.git --branch proversity/master ./config
             cp -r config/gradle.properties OpenEdXMobile/gradle.properties
             cp -r config/google-services.json OpenEdXMobile/google-services.json
             echo "edx.dir = '../config'" > OpenEdXMobile/edx.properties
             cp -r config/config.yaml $CIRCLE_ARTIFACT
       - run:
          name: Install override dependencies
          command: ./gradlew dependencies --stacktrace --info
       - run:
          name: Install post dependencies
          command: |
             git clone git@github.com:proversity-org/edx-app-android-config.git --branch proversity/master ./config
             cp -r config/gradle.properties OpenEdXMobile/gradle.properties
             cp -r config/google-services.json OpenEdXMobile/google-services.json
             echo "edx.dir = '../config'" > OpenEdXMobile/edx.properties
             cp -r config/config.yaml $CIRCLE_ARTIFACTS      
       - run:
          name: Install pre tests
          command: ./gradlew assembleProdRelease
       - run:
          name: Install override tests
          command: ./gradlew testProdReleaseUnitTestCoverage
       - run:
          name: Install post tests
          command: |
             cp -r OpenEdXMobile/build/reports $CIRCLE_ARTIFACTS
             cp -r OpenEdXMobile/build/outputs $CIRCLE_ARTIFACTS
       # https://github.com/Triple-T/gradle-play-publisher
       - deploy:
          command: |
                if [ "${CIRCLE_BRANCH}" == "proversity/master" ]; then
                   ./gradlew publishApkProdRelease -PdisablePreDex -Dorg.gradle.project.track=beta
                fi
notify:
  webhooks:
    - url: https://consola-api.proversity.org/organizations/PRO/circleci/webhook?action=save_last_apk&repo=edx-app-android&authorization=e6005c3173671458fee3b322a73178ca2c900ab8b433c302dbd560ec0ed71570


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: proversity/master

