version: 2

jobs:
  build:

    docker:
      - image: circleci/android:api-25-alpha
    working_directory: ~/edx-app-android
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      RELEASE_PK12_FILE: "../config/release.p12"
      JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
            ./gradlew dependencies --stacktrace --info
      - run:
          name: Setup project
          command: |
            git clone git@github.com:proversity-org/edx-app-android-config.git --branch proversity/cit ./config
            cp -r config/gradle.properties OpenEdXMobile/gradle.properties
            cp -r config/google-services.json OpenEdXMobile/google-services.json
            echo "edx.dir = '../config'" > OpenEdXMobile/edx.properties
            mkdir -p /tmp/core_dumps
            cp -r config/config.yaml /tmp/core_dumps    
      - run:
          name: Build app
          command: |
            ./gradlew cleanBuildCache
            ./gradlew assembleProdRelease
            ./gradlew testProdReleaseUnitTestCoverage
            cp -r OpenEdXMobile/build/reports /tmp/core_dumps
            cp -r OpenEdXMobile/build/outputs /tmp/core_dumps
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "proversity/master" ]; then
              ./gradlew publishApkProdRelease -PdisablePreDex -Dorg.gradle.project.track=beta
            fi
      - store_artifacts:
          path: /tmp/core_dumps

notify:
  webhooks:
    - url: https://consola-api.proversity.org/organizations/CIT/circleci/webhook?action=save_last_apk&repo=edx-app-android&authorization=e6005c3173671458fee3b322a73178ca2c900ab8b433c302dbd560ec0ed71570

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: rc/2.12.1
